## Importing relavent libraries

In [1]:
import numpy as np

### Scalars

In [3]:
s = np.array(10)
type(s)

numpy.ndarray

In [4]:
s.shape

()

### Vectors

In [6]:
v = np.array([7, 10, 17])
type(v)

numpy.ndarray

In [7]:
v.shape

(3,)

### Matrices

In [8]:
m = np.array([[1,2],[3,4]])
type(m)

numpy.ndarray

In [9]:
m.shape

(2, 2)

### Tensors

In [41]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8,9],[10,11,12]])

In [12]:
t = np.array([m1,m2])
t

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
t.shape

(2, 2, 3)

### Manually creating a tensor

In [15]:
t_manual = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
t_manual

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
t_manual.shape

(2, 2, 3)

### Matrix oprtations

In [19]:
m1 + m2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [20]:
m1 - m2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [21]:
m1 * m2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [22]:
m1 / m2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

### Transposing the matrices

In [24]:
m.T

array([[1, 3],
       [2, 4]])

In [25]:
x_test = np.arange(30).reshape(3, 2, 5)

print(x_test)
print(x_test.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
(3, 2, 5)


In [33]:
y = np.transpose(x_test, (1, 2, 0))
print(y)
print(y.shape)

[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]]
(2, 5, 3)


### Dot Product

In [34]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [35]:
np.dot(x,y)

-66

### Scalar with vector

In [37]:
2 * v

array([14, 20, 34])

### Scalar with matrix

In [39]:
3 * m

array([[ 3,  6],
       [ 9, 12]])

### Matrix with Matrix

In [47]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8,9],[10,11,12],[13,14,15]])

In [48]:
np.dot(m1, m2)

array([[ 66,  72,  78],
       [156, 171, 186]])

In [ ]:
x